# Generated by Django 2.2.10 on 2024-05-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='group_name',
            field=models.CharField(default='DEFAULT GROUP', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='file',
            unique_together={('file_name', 'uploaded_time')},
        ),
    ]
