# Generated by Django 4.2.14 on 2024-07-11 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_metrics_belonging_scope_column_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputedMetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('scope', models.CharField(default='Column', max_length=255)),
                ('belonging_scope_column', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.column')),
                ('belonging_scope_dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.file')),
            ],
        ),
        migrations.CreateModel(
            name='MetricType',
            fields=[
                ('metric_type', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Metrics',
        ),
        migrations.AddField(
            model_name='computedmetric',
            name='metric_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.metrictype'),
        ),
    ]
